// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: src/quotes/quotes.proto

package quotes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuotterClient is the client API for Quotter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuotterClient interface {
	GetQuote(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Quote, error)
}

type quotterClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotterClient(cc grpc.ClientConnInterface) QuotterClient {
	return &quotterClient{cc}
}

func (c *quotterClient) GetQuote(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Quote, error) {
	out := new(Quote)
	err := c.cc.Invoke(ctx, "/Quotter/GetQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuotterServer is the server API for Quotter service.
// All implementations must embed UnimplementedQuotterServer
// for forward compatibility
type QuotterServer interface {
	GetQuote(context.Context, *Empty) (*Quote, error)
	mustEmbedUnimplementedQuotterServer()
}

// UnimplementedQuotterServer must be embedded to have forward compatible implementations.
type UnimplementedQuotterServer struct {
}

func (UnimplementedQuotterServer) GetQuote(context.Context, *Empty) (*Quote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedQuotterServer) mustEmbedUnimplementedQuotterServer() {}

// UnsafeQuotterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuotterServer will
// result in compilation errors.
type UnsafeQuotterServer interface {
	mustEmbedUnimplementedQuotterServer()
}

func RegisterQuotterServer(s grpc.ServiceRegistrar, srv QuotterServer) {
	s.RegisterService(&Quotter_ServiceDesc, srv)
}

func _Quotter_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotterServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Quotter/GetQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotterServer).GetQuote(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Quotter_ServiceDesc is the grpc.ServiceDesc for Quotter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Quotter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Quotter",
	HandlerType: (*QuotterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _Quotter_GetQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/quotes/quotes.proto",
}
